language: node_js
node_js:
  - 14

sudo: false

cache:
  directories:
    - node_modules

before_script:
  - npm run build

after_success:
  - npm run coverage-coveralls

env:
  global:
    - secure: VYp1mNGAcEzj+GiGLK/j5mphqJg9cfQknPMkcpeIB35hNhl4UtL2BMjloGy8NtFa7NklbBpX7jW4bbVm8Av70sPCF/zWGX3S7FTFFIQ2wohvbRXiUEtqy1oJbVplQ7Fyfv7SV5Pk7ZKYyDstnXimVVg1OnSSYiF2xX9jffQMZNg=
    - secure: F4wS3zbM9ANoH2FKmXEKe7BhDutDdbDQxkE7FZbP6yJ07GtD1KRQdDMnsy5VHDThStbYVbDLnNOKTqzHsprJ4LFOKldB1k6Zfh8IO/QICHXw3WbkCYjPUY6D1pOnYn8s2KV9Sq2QtT3KY889yXMk/EHFLlu+sopsSrH4py+oOmw=
